### ISSUE TITLE
Where are data/Eclipse_Platform_UI.txt and data/feature.csv files?

### ISSUE THREAD

**Issue by AdnanMuhib** [emredogan7/bug-localization-by-dnn-and-rvsm#1]
hi there,
I am trying to reproduce the same results but unable to find the starting point of the code.
How to extract the features and what path changes to repository and bug reports are required?
What is the format of `Eclipse_Platform_UI.txt` is this a Bug Report in txt format and how to obtain this file?
when  `feature.csv` file is generated and which files are required to generate `feature.csv` file?

**Comment by hacetin** [comment]
You can find the dataset here(It is given in the paper):
http://dx.doi.org/10.6084/m9.figshare.951967

The dataset includes `Eclipse_Platform_UI.xlsx`. `Eclipse_Platform_UI.txt` is the tab separated version of the same file. You can take a look at the dataset to see what is inside it.

As far as I remember,  `Eclipse_Platform_UI.txt` is enough to extract features, and related codes are in [util.py](https://github.com/mrdogan7/bug-localization-by-dnn-and-rvsm/blob/master/Code/util.py).

The repo is not clear about your questions, I will update it and README as soon as possible.

**Comment by AdnanMuhib** [comment]
Thanks @hacetin 
The link you shared contains .xlsx and .xml format of the dataset. And older versions contain .sql dump of the dataset.
Can you please share the .txt format of the dataset.
Thanks

**Comment by mrdogan7** [comment]
Hi @AdnanMuhib ,
Sorry for the delay. @hacetin already explained the process but if you want .txt file go for the [link](https://drive.google.com/file/d/1IDFfyueUhcC_lbjOr5mdU-gfs3rfcS_x/view?usp=sharing) .

**Comment by AdnanMuhib** [comment]
Thanks @hacetin and @mrdogan7 .
Now I can successully load the file using [gitUpdater.py](https://github.com/mrdogan7/bug-localization-by-dnn-and-rvsm/blob/master/Code/gitUpdater.py) which call `tsv2dict()` method from [util.py](https://github.com/mrdogan7/bug-localization-by-dnn-and-rvsm/blob/master/Code/util.py)
and I have commented the line
```
samples = csv2dict()
```
because `csv2dict()` method tries to load the `./data/features.csv` file before the `./data/our_features.csv` file is created also file names are not the same. e.g.
in `gitUpdater.py`
```
bug_reports = tsv2dict()[1199:]
samples = csv2dict() # loads the feature.csv file
our_features_path = os.path.normpath('./data/our_features.csv')
```
and in `util.py`

```
def csv2dict():
file_ = os.path.normpath('./data/features.csv')
```
I have renamed both names of the files to be the same
but I encountered an error during the git checkout I am using the recently cloned [repository](https://github.com/eclipse/eclipse.platform.ui)
Here is the output and error I receive after running the [gitUpdater.py](https://github.com/mrdogan7/bug-localization-by-dnn-and-rvsm/blob/master/Code/gitUpdater.py):
```
Checking out files: 100% (9636/9636), done.
Note: checking out '023b32a'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 023b32a934 Bug 310199 Need logic to grant focus to parts when their tab item has been selected
Previous HEAD position was 023b32a934 Bug 310199 Need logic to grant focus to parts when their tab item has been selected
HEAD is now at 75dfcf09b9 Bug 315907 -  Render menus on SWT.Show
Checking out files: 100% (588/588), done.
Previous HEAD position was 75dfcf09b9 Bug 315907 -  Render menus on SWT.Show
HEAD is now at 012eb4b10e Bug 315401 [Compatibility] Close editors with non-persistable editor inputs on shutdown
Previous HEAD position was 012eb4b10e Bug 315401 [Compatibility] Close editors with non-persistable editor inputs on shutdown
HEAD is now at 4cafe73783 Bug 315381 [Compatibility] Cannot use Alt+Enter to open breakpoint properties
Previous HEAD position was 4cafe73783 Bug 315381 [Compatibility] Cannot use Alt+Enter to open breakpoint properties
HEAD is now at e2ed5aa2a2 Bug 315698 'persistedState' feature not reconciled for existing contributions
Previous HEAD position was e2ed5aa2a2 Bug 315698 'persistedState' feature not reconciled for existing contributions
HEAD is now at 64a518ed2f Bug 315586 -  API typo: IResourceUtiltities
Previous HEAD position was 64a518ed2f Bug 315586 -  API typo: IResourceUtiltities
HEAD is now at 8417e9f40f Bug 315497 -  IWorkbenchWindowHandler obsolete
Previous HEAD position was 8417e9f40f Bug 315497 -  IWorkbenchWindowHandler obsolete
HEAD is now at b585b4169a Bug 315495 -  Remove obsolete ContributionUtils
Previous HEAD position was b585b4169a Bug 315495 -  Remove obsolete ContributionUtils
HEAD is now at 4584dba376 Bug 315481 -  Remove IFocusable
Previous HEAD position was 4584dba376 Bug 315481 -  Remove IFocusable
HEAD is now at d9bf58fc2a Interim fix for Bug 315468 - [UI] Using the MContribution's 'persistedState' field causes a CCE when trying to publish the event. Wire off the publication of the event.
Previous HEAD position was d9bf58fc2a Interim fix for Bug 315468 - [UI] Using the MContribution's 'persistedState' field causes a CCE when trying to publish the event. Wire off the publication of the event.
HEAD is now at 35921a5e39 Bug 308593 [Compatibility] Keybindings seem to be unscoped
Previous HEAD position was 35921a5e39 Bug 308593 [Compatibility] Keybindings seem to be unscoped
HEAD is now at 8a49fe0586 Bug 315132 -  [Compatibility] NPE during shutdown
Checking out files: 100% (6841/6841), done.
Previous HEAD position was 8a49fe0586 Bug 315132 -  [Compatibility] NPE during shutdown
HEAD is now at a4808bfbcb Bug 314102 -  Incorrect summary and missing links on Import/Export Preferences page
Traceback (most recent call last):
  File "gitUpdater.py", line 30, in <module>
    javaFiles = getAllCorpus()
  File "G:\Locus\Bug Localization with DNN\bug-localization-by-dnn-and-rvsm\Code\util.py", line 159, in getAllCorpus
    src_file = open(src_name, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data\\eclipse.platform.ui\\examples\\org.eclipse.ui.examples.views.properties.tabbed.article\\src\\org\\eclipse\\ui\\examples\\views\\properties\\tabbed\\article\\views\\CheckBoxPropertyDescriptor.java'
```

<br>
<br> 
Errors says `FileNotFound` but I looked into the repository and File Exists at the mentioned path in the error. It can be seen in the following screenshot.
<br><br>

![File Exists](https://user-images.githubusercontent.com/18069154/57170412-28924d00-6e26-11e9-8a2a-e3c800757cef.png)
<br><br>
what could possibly be the reason?
Does it has something to do with the gitCheckout at specific commit that file didn't exist (maybe 😁 )?
If yes, can you please suggest a possible solution.
Thanks

**Comment by hacetin** [comment]
As I said in [my first comment](https://github.com/emredogan7/bug-localization-by-dnn-and-rvsm/issues/1#issuecomment-489069100), I refactored most of the source code. If you are still interested you can take look at it.
